import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./providers/query-provider";
import { SheetProvider } from "./providers/sheet-provider";
import { Toaster } from "@/components/ui/toaster";
import UserMenu from "@/components/user-menu";
import TopNav from "@/components/top-nav";
import SearchForm from "@/components/search-form";
import { LDProvider } from "launchdarkly-react-client-sdk";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// A "context" is a data object representing users, devices, organizations, and other entities.
// You'll need this later, but you can ignore it for now.
const ldContext = {
  kind: "user",
  key: "user-key-123abcde",
  email: "biz@face.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LDProvider clientSideID="67c0d10afd2ac409e3384ec3" context={ldContext}>
          <QueryProvider>
            <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
              <SheetProvider />
              <Toaster />
              <TopNav />

              <div className="flex w-full items-center gap-4 md:ml-auto md:gap-2 lg:gap-4">
                <SearchForm />
                <UserMenu />
              </div>
            </header>
            <div className="flex min-h-screen max-w-[1500px] mx-auto flex-col">
              {children}
            </div>
          </QueryProvider>
        </LDProvider>
      </body>
    </html>
  );
}
